name:                creatur
version:             5.9.27
github:              "mhwombat/creatur"
license:             BSD3
author:              "Amy de Buitléir"
maintainer:          "amy@nualeargais.ie"
copyright:           "2018 Amy de Buitléir"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web
synopsis: Framework for artificial life experiments.
category: AI

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mhwombat/creatur#readme>
# description:
#     A software framework for automating experiments
#     with artificial life. It provides a daemon which
#     maintains its own "clock", schedules events,
#     provides logging, and ensures that each agent gets
#     its turn to use the CPU. You can use other
#     applications on the computer at the same time
#     without fear of interfering with experiments; they
#     will run normally, just more slowly. See the
#     tutorial at
#     <https://github.com/mhwombat/creatur-examples/raw/master/Tutorial.pdf>
#     for examples on how to use the
#     Créatúr framework.
#     .
#     About the name: \"Créatúr\" (pronounced kray-toor)
#     is an Irish word meaning animal, creature, or an
#     unfortunate person.

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - array
  - binary
  - bytestring
  - cereal
  - cond
  - directory
  - exceptions
  - filepath
  - gray-extended
  - hdaemonize
  - hsyslog
  - MonadRandom
  - mtl
  - random
  - split
  - time
  - transformers
  - unix

tests:
  creatur-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - creatur
    - cereal
    - directory
    - filepath
    - HUnit
    - MonadRandom
    - mtl
    - QuickCheck
    - temporary
    - test-framework
    - test-framework-hunit
    - test-framework-quickcheck2

